### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by priyadarshan** [TeX-Live/tlcockpit#3]
I just found out about `tlcockpit`, it is a wonderful tool, thank you!

I am using it on FreeBSD (RELEASE-11.1), on a large screen with 110 dpi, and font is quite tiny.

Is there a way to change font size?

Thanks again.

**Comment by norbusan** [comment]
I think this is a Java dependet thing and afair Java does by now not support arbitrary scaling based on dpi. Java9 should (?) improve this, though.

There is probably another way to specify a different font size. On BSD Iguess Java uses Gtk2 (by now, will switch to Gtk3 soon), and you could adjust the default font there?

**Comment by priyadarshan** [comment]
Thank you, I will look at Java documentation.

**Comment by maieul** [comment]
I think it could be useful to have a greater font size by default

**Comment by norbusan** [comment]
I'll look into configuration of the font size

**Comment by ekuester** [comment]
On hiDPI-displays (such as my MacbookPro Retina 13 inch with Fedora Linux) the program is quasi not usable. Window size and font size are only half as they should be, a pain for the eyes ... This is daily reality in the Java programs I am using but ... the other ones have remedies. So you can help yourself invoking the programs with special options (which here do not work!), for instance
`jedit -Dsun.java2d.uiScale=2.0`
`mucommander -Dsun.java2d.uiScale=2.0`
Alternatively you could give the possibility in preferences to choose the font size. Often it is enough to increase the size double high as normal (i.e. 24 instead of 12).
I would highly appreciate if there were such possibilties in this otherwise unblameable program.
In the meantime I must help myself with the old but working
`tlmgr --font 'Helvetica 12' gui`

**Comment by norbusan** [comment]
@ekuester which version of Java are you using? All the signs indicate that recent versions of java8 as well as java9 *do* support hidpi out of the box.

The other options you are mentioning are for Swing applications AFAIR, which doesn't help for ScalaFX/JavaFX.

**Comment by ekuester** [comment]
@norbusan nope, I tested it both with the latest Java jdk1.8.0_161 and jdk-9.0.4 and got the reported results. Ok, I do know little about ScalaFX/JavaFX. Maybe the Mac Retina display is a special candidate, I had issues with it using tvbrowser (TV program guide written in Java). But there I can choose in preferences theme GTK+ and tango icons and all went fine ...

**Comment by mojca** [comment]
It works just fine for me on 15" retina/10.13/JDK 10.

**Comment by norbusan** [comment]
Thanks @mojca for checking. As this is nothing I can influence easily (would need a rewrite in Swing which I don't like) I can only hope that this will be fixed at some point by newer JavaFX/ScalaFX libraries.

**Comment by ekuester** [comment]
@mojka which jdk10 are you using? Would it be sufficient to install the software from [Oracle](http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html)?

**Comment by mojca** [comment]
Yes, I installed it from Oracle. Running `java` brought up a window with a link.

**Comment by ekuester** [comment]
@mojca I assume you are under macOS, because there I have no problems even with Java jdk1.8 ...

Just to test it I installed [jdk10 download](http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html) from Oracle but under Linux ( Fedora 27 ). There is the same behavior as with the older versions :-(( so no success at all.

**Comment by mojca** [comment]
Yes, macOS. I only wrote "10.13" as a reference to retina display mentioned in a previous post.

**Comment by norbusan** [comment]
@ekuester Ahh, you are running Retina display with Linux. I read that the HiDPi support for Retina displays on Mac and Windows is working, but on Linux it is WIP, so I am not surprised that it doesn't work on Linux.

**Comment by ekuester** [comment]
@norbusan Yes, that is the point ... due to some disappointments with Apple I decided to use mostly Linux, which is actually so much better than one should believe ... On my triple-boot-system (macOS/Fedora/Windows10) I could use macOS, but I dont want, not to speak of Windows.

**Comment by norbusan** [comment]
@ekuester whom do you tell ;-) When I was still working at university I had a macpro with retina where I also mostly used Linux instead of MacOS, there I could test all this, but since then I was moved on now I have no chance.

**Comment by ekuester** [comment]
To my disappointment under Linux/Fedora 30 with openjdk version "11.0.4" 2019-07-16 the behaviour on hiDPI displays has not changed (just tested with Dell XPS 13 9380 UHD).

**Comment by norbusan** [comment]
Hi @ekuester 
hmm, no idea. Can you try `-Dsun.java2d.uiScale=2.0` added to the java incantation? And or exporting `export GDK_SCALE=2` in the shell before starting tlcockpit? Does any of these help?

Thanks

**Comment by norbusan** [comment]
Addon, it seems to be fixed in OpenJDK9: https://bugs.openjdk.java.net/browse/JDK-8137050 so I am surprised.

**Comment by ekuester** [comment]
Hi @norbusan,
the -Dsun option does not help (maybe it is only for Oracle Java), but the second advice works on command line:
`$ GDK_SCALE=2 tlcockpit`
GDK_SCALE=3 is perfect for my dell ... so I added `export GDK_SCALE=3` before the last line of the tlcockpit.sh script and am very satisfied.

**Comment by norbusan** [comment]
Great, thanks for the feedback. I have added a paragraph to the readme to clarify HiDPI usage. I guess newer versions will get better support over time.

Closing this bug for now.

Thanks
